swagger: "2.0"
schemes:
- http
- https
host: iam.api.marmotedu.com
basePath: /v1
consumes:
- application/json
produces:
- application/json
info:
  contact:
    email: colin404@foxmail.com
    name: colin
  description: Identity and Access Management system swagger api document
  termsOfService: iam
  title: Identity and Access Management system
  version: 0.1.0
paths:
  /secrets:
    get: 
      tags: 
        - todos
        - get
      parameters:
        - name: expires
          in: header 
          type: integer
          format: int64
          default: 0
        - name: description
          in: header
          type: string
      responses:
        200:
          description: list the todo operations
          schema:
            type: array
            items:
              $ref: '#/definitions/item'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
definitions:
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string

